:global:
  componentName: OpenShift4 Monitoring
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - capacity-alerts
      - release-4.9
      - release-4.10

.gitignore:
  additionalEntries:
    - manifests_requiring_prerendering/
    - jsonnetfile.json

.github/workflows/test.yaml:
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  makeTarget: test -e instance=${{ matrix.instance }}
