= OpenShift4 Monitoring

openshift4-monitoring is a Commodore component to manage OpenShift4 Monitoring.
It creates a ConfigMap in order to configure the monitoring stack of the cluster.

See the xref:references/parameters.adoc[parameters] reference for further details.

[IMPORTANT]
====
This Commodore component violates a warning from the OpenShift 4 documentation.
See xref:explanations/alert_rules.adoc[Alert rules] for the how and the why.
====

== Node Selector

A node selector is configured to only run the monitoring pods on infra nodes.
By doing so, the monitoring can be run on only a subset of the worker nodes.

[IMPORTANT]
====
Ensure that the target cluster does have nodes with the infra role label set.
See the components defaults for the exact value.
====

== Cluster-reader permissions

The component deploys a `ClusterRole` which grants `get`, `list`, and `watch` permissions on all `monitoring.coreos.com` resources.
This `ClusterRole` is configured to be aggregated to the `cluster-reader` `ClusterRole`, thus granting users which have `cluster-reader` read-only access to all `monitoring.coreos.com` resources in the cluster.
