= Parameters

The parent key for all of the following parameters is `openshift4_monitoring`.

== `defaultConfig`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
nodeSelector:
  node-role.kubernetes.io/infra: ''
----

A dictionary holding the default configuration which should be applied to all components.

== `configs`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
prometheusK8s:
  externalLabels:
    cluster_id: ${cluster:name}
    tenant_id: ${cluster:tenant}
  retention: 8d
  volumeClaimTemplate:
    spec:
      resources:
        requests:
          storage: 50Gi
----

A dictionary holding the configurations for the https://docs.openshift.com/container-platform/latest/monitoring/cluster_monitoring/configuring-the-monitoring-stack.html#configurable-monitoring-components_configuring-monitoring[monitoring components].

See the https://docs.openshift.com/container-platform/latest/monitoring/cluster_monitoring/configuring-the-monitoring-stack.html[OpenShift docs] for available parameters.

This table shows the monitoring components you can configure and the keys used to specify the components:

[options="header"]
|====
|Component|Key
|Prometheus Operator|`prometheusOperator`
|Prometheus Operator User Workload|`prometheusOperatorUserWorkload`
|Prometheus|`prometheusK8s`
|Prometheus User Workload|`prometheusUserWorkload`
|Alertmanager|`alertmanagerMain`
|kube-state-metrics|`kubeStateMetrics`
|openshift-state-metrics|`openshiftStateMetrics`
|Grafana|`grafana`
|Telemeter Client|`telemeterClient`
|Prometheus Adapter|`k8sPrometheusAdapter`
|Thanos Querier|`thanosQuerier`
|Thanos Ruler|`thanosRuler`
|====

== `alertManagerConfig`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
route:
  group_wait: 0s
  group_interval: 5s
  repeat_interval: 10m
inhibit_rules:
  # Don't send warning or info if a critical is already firing
  - target_match_re:
      severity: warning|info
    source_match:
      severity: critical
    equal:
      - namespace
      - alertname
  # Don't send info if a warning is already firing
  - target_match_re:
      severity: info
    source_match:
      severity: warning
    equal:
      - namespace
      - alertname
----

A dictionary holding the configuration for the AlertManager.

See the https://docs.openshift.com/container-platform/latest/monitoring/cluster_monitoring/configuring-the-monitoring-stack.html#configuring-alertmanager[OpenShift docs] for available parameters.


== Example

[source,yaml]
----
defaultConfig:
  nodeSelector:
    node-role.kubernetes.io/infra: ''
configs:
  prometheusK8s:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Gi
----
