= Parameters

The parent key for all of the following parameters is `openshift4_monitoring`.

== `manifests_version`

[horizontal]
type:: string
default:: `release-4.7`

Select which version of the upstream alerting (and recording) rules should be used by the component.
This parameter must be changed to match the cluster's OCP4 minor version.

NOTE: Once we've implemented https://syn.tools/syn/SDDs/0027-dynamic-cluster-facts.html[dynamic cluster facts], this parameter will be automatically set based on the value of the reported cluster version.

== `defaultConfig`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
nodeSelector:
  node-role.kubernetes.io/infra: ''
----

A dictionary holding the default configuration which should be applied to all components.

== `enableUserWorkload`

[horizontal]
type:: boolean
default:: false

A parameter to enable https://docs.openshift.com/container-platform/4.7/monitoring/enabling-monitoring-for-user-defined-projects.html[monitoring for user-defined projects].

== `configs`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
prometheusK8s:
  externalLabels:
    cluster_id: ${cluster:name}
    tenant_id: ${cluster:tenant}
  retention: 8d
  volumeClaimTemplate:
    spec:
      resources:
        requests:
          storage: 50Gi
prometheusUserWorkload: ${openshift4_monitoring:configs:prometheusK8s}
alertmanagerMain:
  volumeClaimTemplate:
    spec:
      resources:
        requests:
          storage: 2Gi
----

A dictionary holding the configurations for the https://docs.openshift.com/container-platform/latest/monitoring/cluster_monitoring/configuring-the-monitoring-stack.html#configurable-monitoring-components_configuring-monitoring[monitoring components].

See the https://docs.openshift.com/container-platform/latest/monitoring/cluster_monitoring/configuring-the-monitoring-stack.html[OpenShift docs] for available parameters.

This table shows the monitoring components you can configure and the keys used to specify the components:

[options="header"]
|====
|Component|Key
|Prometheus Operator|`prometheusOperator`
|Prometheus Operator User Workload|`prometheusOperatorUserWorkload`
|Prometheus|`prometheusK8s`
|Prometheus User Workload|`prometheusUserWorkload`
|Alertmanager|`alertmanagerMain`
|kube-state-metrics|`kubeStateMetrics`
|openshift-state-metrics|`openshiftStateMetrics`
|Grafana|`grafana`
|Telemeter Client|`telemeterClient`
|Prometheus Adapter|`k8sPrometheusAdapter`
|Thanos Querier|`thanosQuerier`
|Thanos Ruler|`thanosRuler`
|====

== `alertManagerConfig`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
route:
  group_wait: 0s
  group_interval: 5s
  repeat_interval: 10m
inhibit_rules:
  # Don't send warning or info if a critical is already firing
  - target_match_re:
      severity: warning|info
    source_match:
      severity: critical
    equal:
      - namespace
      - alertname
  # Don't send info if a warning is already firing
  - target_match_re:
      severity: info
    source_match:
      severity: warning
    equal:
      - namespace
      - alertname
----

A dictionary holding the configuration for the AlertManager.

See the https://docs.openshift.com/container-platform/latest/monitoring/cluster_monitoring/configuring-the-monitoring-stack.html#configuring-alertmanager[OpenShift docs] for available parameters.

== `alerts`

[horizontal]
type:: dictionary

Configuration parameters related to influence the resulting alert rules.

=== `ignoreNames`

[horizontal]
type:: list
default:: `[]`

List of https://github.com/prometheus-operator/kube-prometheus[kube-prometheus] alert rule names to be dropped.

=== `customAnnotations`

[horizontal]
type:: dict
default:: `{}`

Maps alert names to sets of custom annotations.
Allows configuring custom annotations for individual alerts.

Example:

[source,yaml]
----
customAnnotations:
  Watchdog:
    runbook_url: https://www.google.com/?q=Watchdog
----

=== `patchRules`
type:: dict
keys:: potential values of parameter `manifests_versions`
default:: See https://github.com/appuio/component-openshift4-monitoring/blob/master/class/defaults.yml[`class/defaults.yml` on GitHub]

The parameter `patchRules` allows users to customize upstream alerts.
The component expects that top-level keys in the parameter correspond to values of parameter `manifests_versions`.
This enables users to selectively patch upstream alerts for a particular OpenShift 4 version.

For each version, the component expects alert names as keys and any alert configuration as values.
See the Prometheus https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/[alerting rules documentation] for extended documentation on configuring alerting rules.

Example:

[source,yaml]
----
patchRules:
  release-4.7:
    SystemMemoryExceedsReservation:
      for: 30m
----

== `silence`

[horizontal]
type:: dict

Parameters to configure the silence CronJob.

=== `schedule`

[horizontal]
type:: string
default:: '0 */4 * * *'

Schedule of the CronJob in cron syntax.

=== `serviceAccountName`

[horizontal]
type:: string
default:: prometheus-k8s

Name of the service account used when running the silence job.
The service account must have permission to access the Alertmanager service through its oAuth proxy.

=== `servingCertsCABundleName`

[horizontal]
type:: string
default:: serving-certs-ca-bundle

Name of the config map containing the CA bundle of the Alertmanager service.

=== `jobHistoryLimit`

[horizontal]
type:: dict

Parameters to configure the numbers of silence job objects to keep.

==== `failed`

[horizontal]
type:: number
default:: 3

Number of failed jobs to keep.

==== `successful`

[horizontal]
type:: number
default:: 3

Number of successful jobs to keep.

== Example

[source,yaml]
----
defaultConfig:
  nodeSelector:
    node-role.kubernetes.io/infra: ''
configs:
  prometheusK8s:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Gi
alerts:
  ignoreNames:
    - KubeAPIErrorsHigh
    - KubeClientErrors
----
